#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCREEN 0
#define TRANSITION_TIME 0.5

#define PUFF_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define COLLECTION_COLLISION_BITMASK 0x000003
#define FINISH_COLLISION_BITMASK 0x000004

#define MOVEMENT_SPEED 0.01


#endif // __DEFINITIONS_H__
